// Auth
export const REGISTER_USER="REGISTER_USER";
export const REGISTER_USER_FAILED="REGISTER_USER_FAILED";
export const LOGIN_USER="LOGIN_USER";
export const LOGIN_USER_FAILED="LOGIN_USER_FAILED";

//User
export const LOAD_USER="LOAD_USER";
export const LOAD_USER_FAILED="LOAD_USER_FAILED";

// Calendar
export const LOAD_CALENDARS="LOAD_CALENDARS";
export const IMPORT_CALENDARS="IMPORT_CALENDARS";
export const NEW_CALENDAR="NEW_CALENDAR";
export const UPDATE_CALENDAR="UPDATE_CALENDAR";
export const DELETE_CALENDAR="DELETE_CALENDAR";
export const LOAD_CALENDARS_FAILED="LOAD_CALENDARS_FAILED";
export const IMPORT_CALENDARS_FAILED="IMPORT_CALENDARS_FAILED";
export const NEW_CALENDAR_FAILED="NEW_CALENDAR_FAILED";
export const UPDATE_CALENDAR_FAILED="UPDATE_CALENDAR_FAILED";
export const DELETE_CALENDAR_FAILED="DELETE_CALENDAR_FAILED";

//Date
export const UPDATE_SELECTED_DATE="UPDATE_SELECTED_DATE";
export const UPDATE_VIEW_DATE="UPDATE_VIEW_DATE";

// Event
export const LOAD_EVENTS="LOAD_EVENTS";
export const NEW_EVENT="NEW_EVENT";
export const UPDATE_EVENT="UPDATE_EVENT";
export const DELETE_EVENT="DELETE_EVENT";
export const LOAD_EVENTS_FAILED="LOAD_EVENTS_FAILED";
export const NEW_EVENT_FAILED="NEW_EVENT_FAILED";
export const UPDATE_EVENT_FAILED="UPDATE_EVENT_FAILED";
export const DELETE_EVENT_FAILED="DELETE_EVENT_FAILED";

//Notification
export const LOAD_NOTITFICATIONS="LOAD_NOTITFICATIONS";
export const LOAD_NOTITFICATIONS_FAILED="LOAD_NOTITFICATIONS_FAILED";

//Routes
export const ROUTE_LOGIN="ROUTE_LOGIN";
export const ROUTE_REGISTER="ROUTE_REGISTER";
export const ROUTE_HOME="ROUTE_HOME";