# Generated by Django 2.1.4 on 2018-12-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='users',
            new_name='user',
        ),
    ]
