# Generated by Django 2.1.4 on 2018-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
